#pragma once
#include "view_matrix_configs.h"
void add_more_matrix_configs();
void add_robot_lab_matrix_configs0();
void add_robot_lab_matrix_configs1();
void add_robot_lab_matrix_configs2();
void add_robot_lab_matrix_configs3();
void add_viking_village_matrix_configs0();
void add_viking_village_matrix_configs1();
void add_viking_village_matrix_configs2();
void add_viking_village_matrix_configs3();
void add_sponza_matrix_configs0();
void add_sponza_matrix_configs1();
void add_sponza_matrix_configs2();
void add_sponza_matrix_configs3();
void add_bistro_matrix_configs0();
void add_bistro_matrix_configs1();
void add_bistro_matrix_configs2();
void add_bistro_matrix_configs3();
void add_gallery_matrix_configs0();
void add_gallery_matrix_configs1();
void add_gallery_matrix_configs2();
void add_gallery_matrix_configs3();
void add_san_miguel_matrix_configs0();
void add_san_miguel_matrix_configs1();
void add_san_miguel_matrix_configs2();
void add_san_miguel_matrix_configs3();
