#version 460

layout(std430, binding = 2) buffer PrimitiveEnabledBuffer
{
	uint primitiveEnabled[];
};

layout (binding = 5, offset = 0) uniform atomic_uint uPrimitiveCounter;

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;
void main()
{
	if (uint(gl_GlobalInvocationID.x) < primitiveEnabled.length()) 
	{
		if (primitiveEnabled[uint(gl_GlobalInvocationID.x)] == 1) {
			atomicCounterIncrement(uPrimitiveCounter);
		}
	}
}
